// PRODUCT GET LIST
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// PRODUCT GET BY ID
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_FAIL = 'PRODUCT_GET_FAIL';

// PRODUCT UPDATE BY ID
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';

// PRODUCT ADD STOCKS
export const PRODUCT_ADD_STOCKS_SUCCESS = 'PRODUCT_ADD_STOCKS_SUCCESS';
export const PRODUCT_ADD_STOCKS_FAIL = 'PRODUCT_ADD_STOCKS_FAIL';

// ORDER GET LIST
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

// ORDER ADD
export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS';
export const ORDER_ADD_FAIL = 'ORDER_ADD_FAIL';

// ORDER GET DETAILS
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

// ORDER UPDATE DETAILS
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

// ORDER ADD ITEM
export const ORDER_ADD_ITEM_SUCCESS = 'ORDER_ADD_ITEM_SUCCESS';
export const ORDER_ADD_ITEM_FAIL = 'ORDER_ADD_ITEM_FAIL';

// ORDER ITEM LIST
export const ORDER_ITEM_LIST_SUCCESS = 'ORDER_ITEM_LIST_SUCCESS';
export const ORDER_ITEM_LIST_FAIL = 'ORDER_ITEM_LIST_FAIL';

// DELIVERY LIST
export const DELIVERY_LIST_SUCCESS = 'DELIVERY_LIST_SUCCESS';
export const DELIVERY_LIST_FAIL = 'DELIVERY_LIST_FAIL';

// ADD DELIVERY
export const DELIVERY_ADD_SUCCESS = 'DELIVERY_ADD_SUCCESS';
export const DELIVERY_ADD_FAIL = 'DELIVERY_ADD_FAIL';

// DEETS DELIVERY
export const DELIVERY_DETAILS_SUCCESS = 'DELIVERY_DETAILS_SUCCESS';
export const DELIVERY_DETAILS_FAIL = 'DELIVERY_DETAILS_FAIL';

// UPDATE DELIVERY
export const DELIVERY_UPDATE_SUCCESS = 'DELIVERY_UPDATE_SUCCESS';
export const DELIVERY_UPDATE_FAIL = 'DELIVERY_UPDATE_FAIL';

// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
