// PRODUCT GET LIST
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// PRODUCT GET BY ID
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_FAIL = 'PRODUCT_GET_FAIL';

// PRODUCT UPDATE BY ID
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL';

// PRODUCT DELETE BY ID
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETEE_FAIL';

// PRODUCT ADD STOCKS
export const PRODUCT_ADD_STOCKS_SUCCESS = 'PRODUCT_ADD_STOCKS_SUCCESS';
export const PRODUCT_ADD_STOCKS_FAIL = 'PRODUCT_ADD_STOCKS_FAIL';

// PRODUCT ADD STOCKS
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';

// ORDER GET LIST
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

// ORDER ADD
export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS';
export const ORDER_ADD_FAIL = 'ORDER_ADD_FAIL';

// ORDER GET DETAILS
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

// ORDER ITEM GET DETAILS

export const ORDER_ITEM_DETAILS_SUCCESS = 'ORDER_ITEM_DETAILS_SUCCESS';
export const ORDER_ITEM_DETAILS_FAIL = 'ORDER_ITEM_DETAILS_FAIL';

export const ORDER_ITEM_REMOVE_SUCCESS = 'ORDER_ITEM_REMOVE_SUCCESS';
export const ORDER_ITEM_REMOVE_FAIL = 'ORDER_ITEM_REMOVE_FAIL';

export const ORDER_REMOVE_SUCCESS = 'ORDER_REMOVE_SUCCESS';
export const ORDER_REMOVE_FAIL = 'ORDER_REMOVE_FAIL';

export const ORDER_ITEM_UPDATE_SUCCESS = 'ORDER_ITEM_UPDATE_SUCCESS';
export const ORDER_ITEM_UPDATE_FAIL = 'ORDER_ITEM_UPDATE_FAIL';

// ORDER UPDATE DETAILS
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

// ORDER ADD ITEM
export const ORDER_ADD_ITEM_SUCCESS = 'ORDER_ADD_ITEM_SUCCESS';
export const ORDER_ADD_ITEM_FAIL = 'ORDER_ADD_ITEM_FAIL';

// ORDER ITEM LIST
export const ORDER_ITEM_LIST_SUCCESS = 'ORDER_ITEM_LIST_SUCCESS';
export const ORDER_ITEM_LIST_FAIL = 'ORDER_ITEM_LIST_FAIL';

// DELIVERY LIST
export const DELIVERY_LIST_SUCCESS = 'DELIVERY_LIST_SUCCESS';
export const DELIVERY_LIST_FAIL = 'DELIVERY_LIST_FAIL';

// ADD DELIVERY
export const DELIVERY_ADD_SUCCESS = 'DELIVERY_ADD_SUCCESS';
export const DELIVERY_ADD_FAIL = 'DELIVERY_ADD_FAIL';

// DEETS DELIVERY
export const DELIVERY_DETAILS_SUCCESS = 'DELIVERY_DETAILS_SUCCESS';
export const DELIVERY_DETAILS_FAIL = 'DELIVERY_DETAILS_FAIL';

// UPDATE DELIVERY
export const DELIVERY_UPDATE_SUCCESS = 'DELIVERY_UPDATE_SUCCESS';
export const DELIVERY_UPDATE_FAIL = 'DELIVERY_UPDATE_FAIL';

// UPDATE DELIVERY
export const DELIVERY_REMOVE_SUCCESS = 'DELIVERY_REMOVE_SUCCESS';
export const DELIVERY_REMOVE_FAIL = 'DELIVERY_REMOVE_FAIL';

// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';


// USER
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';
export const USER_ADD_FAIL = 'USER_ADD_FAIL';

export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAIL = 'USER_GET_FAIL';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

// GET CATEGORY
export const CATEGORY_GET_SUCCESS = "CATEGORY_GET_SUCCESS";
export const CATEGORY_GET_FAIL = "CATEGORY_GET_FAIL";

export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";

export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";


export const USER_VERIFY_SUCCESS = "USER_VERIFY_SUCCESS";
export const USER_VERIFY_FAIL = "USER_VERIFY_FAIL";

export const EMPLOYEE_ADD_SUCCESS = 'EMPLOYEE_ADD_SUCCESS';
export const EMPLOYEE_ADD_FAIL = 'EMPLOYEE_ADD_FAIL';

export const REQUEST_NEW_PASSWORD_SUCCESS = 'REQUEST_NEW_PASSWORD_SUCCESS';
export const REQUEST_NEW_PASSWORD_FAIL = 'REQUEST_NEW_PASSWORD_FAIL';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

// GENERATE REPORT
export const ORDDER_GENERATE_PDF_REPORT_SUCCESS = 'ORDDER_GENERATE_PDF_REPORT_SUCCESS';
export const ORDDER_GENERATE_PDF_REPORT_FAIL = 'ORDDER_GENERATE_PDF_REPORT_FAIL';


// NOTIFICATION LIST
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL';

// NOTIFICATION LIST
export const NOTIFICATION_UPDATE_SUCCESS = 'NOTIFICATION_UPDATE_SUCCESS';
export const NOTIFICATION_UPDATE_FAIL = 'NOTIFICATION_UPDATE_FAIL';
